basic_route:
    path:       /
    defaults:   {_controller: 'basic_page_controller::indexAction'}
    methods:    [GET, HEAD]
    
basic_index_route:
    path:       /index
    defaults:   {_controller: 'basic_page_controller::indexAction'}
    methods:    [GET, HEAD]
    
summit_route:
    path:       /summit
    defaults:   {_controller: 'summit_controller::indexAction'}
    methods:    [GET, HEAD]
    
api_data_route:
    path:       /api
    defaults:   {_controller: 'api_controller::dataAction'}
    methods:    [GET, HEAD]
    
api_mailer_route:
    path:       /apimail
    defaults:   {_controller: 'api_controller::mailAction'}
    methods:    [GET, HEAD]