parameters:
    template_dir:   '../templates'
    data_dir:       '../data'

services:
#    twig services
    loader:
        class:      Twig_Loader_Filesystem
        arguments:  ['%template_dir%']
    twig:
        class:      Twig_Environment
        arguments:  ['@loader']

#filesystem services
    adapter:
        class:      League\Flysystem\Adapter\Local
        arguments:  ['%data_dir%']
    filesystem:
        class:      League\Flysystem\Filesystem
        arguments:  ['@adapter']

# services for controllers
    layout_service:
        class:      Turtle\Service\LayoutService
        arguments:  ['@filesystem']
    template_service:
        class:      Turtle\Service\TemplateService
        arguments:  ['@twig', '@layout_service']
                
# controllers
    basic_page_controller:
        class:      Turtle\Controller\BasicPageController
        arguments:  ['@template_service', '@layout_service']
